insert into AccountInfo values(null, 'jack123', '12345', 'example@email.com' ,0);
insert into AccountInfo values(null, 'rose123', '12345', 'example@email.com' ,0);
insert into AccountInfo values(null, 'guerry123', '12345', 'example@email.com' ,0);
insert into AccountInfo values(null, 'perry123', '12345', 'example@email.com' ,0);
insert into AccountInfo values(null, 'mary123', '12345', 'example@email.com' ,0);
insert into AccountInfo values(null, 'john123', '12345', 'example@email.com' ,0);
insert into AccountInfo values(null, 'jake123', '12345', 'example@email.com' ,0);
insert into AccountInfo values(null, 'edsion123', '12345', 'example@email.com' ,0);
insert into AccountInfo values(null, 'luke123', '12345', 'example@email.com' ,0);

insert into FriendInfo values(2, 4, '同学');
insert into FriendInfo values(2, 5, '同学');
insert into FriendInfo values(2, 6, '同学');
insert into FriendInfo values(2, 7, '同学');
insert into FriendInfo values(2, 8, '同学');
insert into FriendInfo values(2, 9, '同学');
insert into FriendInfo values(3, 4, '老同学');
insert into FriendInfo values(3, 5, '老同学');
insert into FriendInfo values(3, 6, '老同学');
insert into FriendInfo values(3, 7, '老同学');
insert into FriendInfo values(3, 8, '老同学');
insert into FriendInfo values(3, 9, '老同学');
insert into FriendInfo values(3, 10, '1070寝室');
